project:
  type: website

website:
  back-to-top-navigation: true
  sidebar:
    title: "Data Science"
    background: light
    pinned: true
    style: "docked"
    search: true
    contents:
      - section: "STAT4500"  
        href: stat4500.qmd   
        contents:
          - text: "Resourses"
            href: index.qmd
  page-footer: "Copyright 2026, Xiao Ling@AUM"
  
format:
  html:
    toc: true           
    toc-location: right  
    toc-depth: 4
    number-sections: true   
    page-layout: full
          